using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Evac.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Evac.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESEvacBeaconWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public ESEvacBeaconWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateStationStatuses();
    }

    public void UpdateStationStatuses()
    {
        StationStatusNameContainer.Children.Clear();
        StationStatusStateContainer.Children.Clear();

        var query = _entityManager.EntityQueryEnumerator<ESEvacBeaconComponent, MetaDataComponent>();
        while (query.MoveNext(out _, out var beacon, out var meta))
        {
            StationStatusNameContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("es-evac-computer-ui-station-list-name-fmt", ("name", meta.EntityName)),
            });
            StationStatusStateContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString(beacon.Enabled
                    ? "es-evac-computer-ui-station-list-status-on"
                    : "es-evac-computer-ui-station-list-status-off"),
            });
        }
    }
}

