using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Multistation.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESDepartmentHeader : BoxContainer
{
    public ESDepartmentHeader()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetDepartment(DepartmentPrototype department)
    {
        BackgroundPanel.PanelOverride = new StyleBoxFlat(department.Color);
        DepartmentNameLabel.Text = Loc.GetString("es-spawn-menu-job-department-format",
            ("department", Loc.GetString(department.Name)));
    }
}

