// ES START
// completely modified from old file pretty much
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
            // ES START
            SetAnchorPreset(MainViewport, LayoutPreset.Wide);
            SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
            SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
            SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
            SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);
            // ES END

            //LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            //CollapseButton.OnPressed += _ => TogglePanel(false);
            //ExpandButton.OnPressed += _ => TogglePanel(true);
        }

        public void SwitchState(LobbyGuiState state)
        {
            ViewportContainer.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    ViewportContainer.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            //RightSide.Visible = value;
            //ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
