using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._ES.Spawning.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStationCheckbox : BoxContainer
{
    public event Action<EntityUid>? OnPressed;

    public EntityUid Station { get; private set; }

    public bool Pressed => CheckBox.Pressed;

    public ESStationCheckbox()
    {
        RobustXamlLoader.Load(this);
    }

    public ESStationCheckbox(EntityUid station, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);

        CheckBox.OnPressed += _ =>
        {
            OnPressed?.Invoke(station);
        };
        StationLabel.Text = entMan.GetComponent<MetaDataComponent>(station).EntityName;
        Station = station;
    }

    public void SetClickPressed(bool value)
    {
        CheckBox.SetClickPressed(value);
        OnPressed?.Invoke(Station);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick)
            return;

        SetClickPressed(!CheckBox.Pressed);
    }
}

